### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rammicz**
New mongo driver 2.4.4 and framework 4.5.2

### CODE REVIEW

**Comment by rammicz** [comment]
Hello, I would like to use your MongoProviders for Microsoft Cosmos DB, I'm getting it working right now, but it should be still compatible with mongo, Main difference is, Cosmos creates indexes itself, so there is no need / possibility to create indexes on your own. As a first step, please take this upgrade to the latest mongo driver 2.4.4

**Comment by alanning** [comment]
Hi rammicz, thank you for the pull request.  This is quite an old project, is it still useful?  I can merge PR's but don't have a way to test changes so I'm a little leery of doing so.

Would you like to maintain a version of this?  I could update the readme to send people to your version as an "up-to-date" version.  What do you think?

**Comment by rammicz** [comment]
Hello Adrian,

I am pretty new on github, so my pull request was actually from a bad
version, I did not fully understand the "pull request" at the time, please
ignore it.

I've commited big part of the rework yesterday. I'm planning to use it on
my Azure / CosmosDB, which is compatible with mongo API.
I've got it working yesterday, all tests are green. I did not get it fully
integrated into my webapp yet, but so far no errors found.

I can hold the fork on my account, no problem. If you're not going to
support it, I can also create my own nuget from the fork.

So yes please, if you can point the link to my fork, it seems I will work
on it for a while.

Thanks for reaching me,
Jiri



2017-08-08 21:20 GMT+02:00 Adrian Lanning <notifications@github.com>:

**Comment by alanning** [comment]
OK, thanks.  Please let me know once your fork is up to date and send me a link here.  I'll update the readme to send people to your version.  :-)

**Comment by alanning** [comment]
@rammicz Hi, thanks for the update.  :-)

**Pull request closed without merging**
